version: '3'
services:
  rwdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: realworld # automatically create database
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql