// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: realworld/v1/realworld.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{0}
}

type FavoriteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteArticleRequest) Reset() {
	*x = FavoriteArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteArticleRequest) ProtoMessage() {}

func (x *FavoriteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteArticleRequest.ProtoReflect.Descriptor instead.
func (*FavoriteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{1}
}

func (x *FavoriteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type UnfavoriteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteArticleRequest) Reset() {
	*x = UnfavoriteArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteArticleRequest) ProtoMessage() {}

func (x *UnfavoriteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteArticleRequest.ProtoReflect.Descriptor instead.
func (*UnfavoriteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{2}
}

func (x *UnfavoriteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCommentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DeleteCommentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommentsRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type AddCommentRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Comment       *AddCommentRequest_Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Slug          string                     `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{6}
}

func (x *AddCommentRequest) GetComment() *AddCommentRequest_Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *AddCommentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Article       *UpdateArticleRequest_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Slug          string                        `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArticleRequest) GetArticle() *UpdateArticleRequest_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *UpdateArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Article       *CreateArticleRequest_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{10}
}

func (x *CreateArticleRequest) GetArticle() *CreateArticleRequest_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type FeedArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedArticlesRequest) Reset() {
	*x = FeedArticlesRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedArticlesRequest) ProtoMessage() {}

func (x *FeedArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedArticlesRequest.ProtoReflect.Descriptor instead.
func (*FeedArticlesRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{11}
}

func (x *FeedArticlesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FeedArticlesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{12}
}

func (x *GetArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Favorited     string                 `protobuf:"bytes,3,opt,name=favorited,proto3" json:"favorited,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{13}
}

func (x *ListArticlesRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListArticlesRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListArticlesRequest) GetFavorited() string {
	if x != nil {
		return x.Favorited
	}
	return ""
}

func (x *ListArticlesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArticlesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{14}
}

func (x *UnfollowUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{15}
}

func (x *FollowUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{16}
}

func (x *GetProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	User          *UpdateUserRequest_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserRequest) GetUser() *UpdateUserRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{18}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *LoginRequest_User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{19}
}

func (x *LoginRequest) GetUser() *LoginRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *RegisterRequest_User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterRequest) GetUser() *RegisterRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

// 通用
type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserResponse_User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{21}
}

func (x *UserResponse) GetUser() *UserResponse_User {
	if x != nil {
		return x.User
	}
	return nil
}

type ProfileResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Profile       *ProfileResponse_Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{22}
}

func (x *ProfileResponse) GetProfile() *ProfileResponse_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SingleArticleResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Article       *SingleArticleResponse_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleArticleResponse) Reset() {
	*x = SingleArticleResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleArticleResponse) ProtoMessage() {}

func (x *SingleArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleArticleResponse.ProtoReflect.Descriptor instead.
func (*SingleArticleResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{23}
}

func (x *SingleArticleResponse) GetArticle() *SingleArticleResponse_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type MultipleArticleResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Articles      []*MultipleArticleResponse_Articles `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	ArticlesCount uint32                              `protobuf:"varint,2,opt,name=articles_count,json=articlesCount,proto3" json:"articles_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleArticleResponse) Reset() {
	*x = MultipleArticleResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticleResponse) ProtoMessage() {}

func (x *MultipleArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticleResponse.ProtoReflect.Descriptor instead.
func (*MultipleArticleResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{24}
}

func (x *MultipleArticleResponse) GetArticles() []*MultipleArticleResponse_Articles {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *MultipleArticleResponse) GetArticlesCount() uint32 {
	if x != nil {
		return x.ArticlesCount
	}
	return 0
}

type SingleCommentResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Comment       *SingleCommentResponse_Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleCommentResponse) Reset() {
	*x = SingleCommentResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleCommentResponse) ProtoMessage() {}

func (x *SingleCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleCommentResponse.ProtoReflect.Descriptor instead.
func (*SingleCommentResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{25}
}

func (x *SingleCommentResponse) GetComment() *SingleCommentResponse_Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type MultipleCommentResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Comments      []*MultipleCommentResponse_Comments `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleCommentResponse) Reset() {
	*x = MultipleCommentResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleCommentResponse) ProtoMessage() {}

func (x *MultipleCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleCommentResponse.ProtoReflect.Descriptor instead.
func (*MultipleCommentResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{26}
}

func (x *MultipleCommentResponse) GetComments() []*MultipleCommentResponse_Comments {
	if x != nil {
		return x.Comments
	}
	return nil
}

type TagsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsListResponse) Reset() {
	*x = TagsListResponse{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsListResponse) ProtoMessage() {}

func (x *TagsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsListResponse.ProtoReflect.Descriptor instead.
func (*TagsListResponse) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{27}
}

func (x *TagsListResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddCommentRequest_Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest_Comment) Reset() {
	*x = AddCommentRequest_Comment{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest_Comment) ProtoMessage() {}

func (x *AddCommentRequest_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest_Comment.ProtoReflect.Descriptor instead.
func (*AddCommentRequest_Comment) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{6, 0}
}

func (x *AddCommentRequest_Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type UpdateArticleRequest_Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TagList       []string               `protobuf:"bytes,4,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest_Article) Reset() {
	*x = UpdateArticleRequest_Article{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest_Article) ProtoMessage() {}

func (x *UpdateArticleRequest_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest_Article.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateArticleRequest_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdateArticleRequest_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

type CreateArticleRequest_Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TagList       []string               `protobuf:"bytes,4,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest_Article) Reset() {
	*x = CreateArticleRequest_Article{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest_Article) ProtoMessage() {}

func (x *CreateArticleRequest_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest_Article.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{10, 0}
}

func (x *CreateArticleRequest_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateArticleRequest_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

type UpdateUserRequest_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest_User) Reset() {
	*x = UpdateUserRequest_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest_User) ProtoMessage() {}

func (x *UpdateUserRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest_User.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{17, 0}
}

func (x *UpdateUserRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest_User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserRequest_User) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type LoginRequest_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest_User) Reset() {
	*x = LoginRequest_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest_User) ProtoMessage() {}

func (x *LoginRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest_User.ProtoReflect.Descriptor instead.
func (*LoginRequest_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{19, 0}
}

func (x *LoginRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest_User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequest_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest_User) Reset() {
	*x = RegisterRequest_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest_User) ProtoMessage() {}

func (x *RegisterRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest_User.ProtoReflect.Descriptor instead.
func (*RegisterRequest_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{20, 0}
}

func (x *RegisterRequest_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest_User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse_User) Reset() {
	*x = UserResponse_User{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse_User) ProtoMessage() {}

func (x *UserResponse_User) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse_User.ProtoReflect.Descriptor instead.
func (*UserResponse_User) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{21, 0}
}

func (x *UserResponse_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse_User) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserResponse_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse_User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserResponse_User) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type ProfileResponse_Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse_Profile) Reset() {
	*x = ProfileResponse_Profile{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse_Profile) ProtoMessage() {}

func (x *ProfileResponse_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse_Profile.ProtoReflect.Descriptor instead.
func (*ProfileResponse_Profile) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{22, 0}
}

func (x *ProfileResponse_Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileResponse_Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileResponse_Profile) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProfileResponse_Profile) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type SingleArticleResponse_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleArticleResponse_Author) Reset() {
	*x = SingleArticleResponse_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleArticleResponse_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleArticleResponse_Author) ProtoMessage() {}

func (x *SingleArticleResponse_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleArticleResponse_Author.ProtoReflect.Descriptor instead.
func (*SingleArticleResponse_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{23, 0}
}

func (x *SingleArticleResponse_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SingleArticleResponse_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *SingleArticleResponse_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SingleArticleResponse_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type SingleArticleResponse_Article struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Slug           string                        `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Body           string                        `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TagList        []string                      `protobuf:"bytes,5,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
	CreatedAt      *timestamppb.Timestamp        `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp        `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Favorited      bool                          `protobuf:"varint,8,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount uint32                        `protobuf:"varint,9,opt,name=favorites_count,json=favoritesCount,proto3" json:"favorites_count,omitempty"`
	Author         *SingleArticleResponse_Author `protobuf:"bytes,10,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SingleArticleResponse_Article) Reset() {
	*x = SingleArticleResponse_Article{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleArticleResponse_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleArticleResponse_Article) ProtoMessage() {}

func (x *SingleArticleResponse_Article) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleArticleResponse_Article.ProtoReflect.Descriptor instead.
func (*SingleArticleResponse_Article) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{23, 1}
}

func (x *SingleArticleResponse_Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SingleArticleResponse_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SingleArticleResponse_Article) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SingleArticleResponse_Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SingleArticleResponse_Article) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *SingleArticleResponse_Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SingleArticleResponse_Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SingleArticleResponse_Article) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

func (x *SingleArticleResponse_Article) GetFavoritesCount() uint32 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *SingleArticleResponse_Article) GetAuthor() *SingleArticleResponse_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type MultipleArticleResponse_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleArticleResponse_Author) Reset() {
	*x = MultipleArticleResponse_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticleResponse_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticleResponse_Author) ProtoMessage() {}

func (x *MultipleArticleResponse_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticleResponse_Author.ProtoReflect.Descriptor instead.
func (*MultipleArticleResponse_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{24, 0}
}

func (x *MultipleArticleResponse_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MultipleArticleResponse_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *MultipleArticleResponse_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MultipleArticleResponse_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type MultipleArticleResponse_Articles struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Slug           string                          `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TagList        []string                        `protobuf:"bytes,4,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
	CreatedAt      *timestamppb.Timestamp          `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp          `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Favorited      bool                            `protobuf:"varint,7,opt,name=favorited,proto3" json:"favorited,omitempty"`
	FavoritesCount uint32                          `protobuf:"varint,8,opt,name=favorites_count,json=favoritesCount,proto3" json:"favorites_count,omitempty"`
	Author         *MultipleArticleResponse_Author `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultipleArticleResponse_Articles) Reset() {
	*x = MultipleArticleResponse_Articles{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleArticleResponse_Articles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleArticleResponse_Articles) ProtoMessage() {}

func (x *MultipleArticleResponse_Articles) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleArticleResponse_Articles.ProtoReflect.Descriptor instead.
func (*MultipleArticleResponse_Articles) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{24, 1}
}

func (x *MultipleArticleResponse_Articles) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MultipleArticleResponse_Articles) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MultipleArticleResponse_Articles) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MultipleArticleResponse_Articles) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *MultipleArticleResponse_Articles) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MultipleArticleResponse_Articles) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MultipleArticleResponse_Articles) GetFavorited() bool {
	if x != nil {
		return x.Favorited
	}
	return false
}

func (x *MultipleArticleResponse_Articles) GetFavoritesCount() uint32 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

func (x *MultipleArticleResponse_Articles) GetAuthor() *MultipleArticleResponse_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type SingleCommentResponse_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleCommentResponse_Author) Reset() {
	*x = SingleCommentResponse_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleCommentResponse_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleCommentResponse_Author) ProtoMessage() {}

func (x *SingleCommentResponse_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleCommentResponse_Author.ProtoReflect.Descriptor instead.
func (*SingleCommentResponse_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{25, 0}
}

func (x *SingleCommentResponse_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SingleCommentResponse_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *SingleCommentResponse_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SingleCommentResponse_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type SingleCommentResponse_Comment struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            uint32                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp        `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp        `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Body          string                        `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author        *SingleCommentResponse_Author `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleCommentResponse_Comment) Reset() {
	*x = SingleCommentResponse_Comment{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleCommentResponse_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleCommentResponse_Comment) ProtoMessage() {}

func (x *SingleCommentResponse_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleCommentResponse_Comment.ProtoReflect.Descriptor instead.
func (*SingleCommentResponse_Comment) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{25, 1}
}

func (x *SingleCommentResponse_Comment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SingleCommentResponse_Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SingleCommentResponse_Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SingleCommentResponse_Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SingleCommentResponse_Comment) GetAuthor() *SingleCommentResponse_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type MultipleCommentResponse_Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Following     bool                   `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleCommentResponse_Author) Reset() {
	*x = MultipleCommentResponse_Author{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleCommentResponse_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleCommentResponse_Author) ProtoMessage() {}

func (x *MultipleCommentResponse_Author) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleCommentResponse_Author.ProtoReflect.Descriptor instead.
func (*MultipleCommentResponse_Author) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{26, 0}
}

func (x *MultipleCommentResponse_Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MultipleCommentResponse_Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *MultipleCommentResponse_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MultipleCommentResponse_Author) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

type MultipleCommentResponse_Comments struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Id            uint32                          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp          `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp          `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Body          string                          `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Author        *MultipleCommentResponse_Author `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleCommentResponse_Comments) Reset() {
	*x = MultipleCommentResponse_Comments{}
	mi := &file_realworld_v1_realworld_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleCommentResponse_Comments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleCommentResponse_Comments) ProtoMessage() {}

func (x *MultipleCommentResponse_Comments) ProtoReflect() protoreflect.Message {
	mi := &file_realworld_v1_realworld_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleCommentResponse_Comments.ProtoReflect.Descriptor instead.
func (*MultipleCommentResponse_Comments) Descriptor() ([]byte, []int) {
	return file_realworld_v1_realworld_proto_rawDescGZIP(), []int{26, 1}
}

func (x *MultipleCommentResponse_Comments) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MultipleCommentResponse_Comments) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MultipleCommentResponse_Comments) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MultipleCommentResponse_Comments) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MultipleCommentResponse_Comments) GetAuthor() *MultipleCommentResponse_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

var File_realworld_v1_realworld_proto protoreflect.FileDescriptor

const file_realworld_v1_realworld_proto_rawDesc = "" +
	"\n" +
	"\x1crealworld/v1/realworld.proto\x12\frealworld.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eGetTagsRequest\",\n" +
	"\x16FavoriteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\".\n" +
	"\x18UnfavoriteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\":\n" +
	"\x14DeleteCommentRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\x12GetCommentsRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x89\x01\n" +
	"\x11AddCommentRequest\x12A\n" +
	"\acomment\x18\x01 \x01(\v2'.realworld.v1.AddCommentRequest.CommentR\acomment\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x1a\x1d\n" +
	"\aComment\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"*\n" +
	"\x14DeleteArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"1\n" +
	"\x15DeleteArticleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe2\x01\n" +
	"\x14UpdateArticleRequest\x12D\n" +
	"\aarticle\x18\x01 \x01(\v2*.realworld.v1.UpdateArticleRequest.ArticleR\aarticle\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x1ap\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x19\n" +
	"\btag_list\x18\x04 \x03(\tR\atagList\"\xce\x01\n" +
	"\x14CreateArticleRequest\x12D\n" +
	"\aarticle\x18\x01 \x01(\v2*.realworld.v1.CreateArticleRequest.ArticleR\aarticle\x1ap\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x19\n" +
	"\btag_list\x18\x04 \x03(\tR\atagList\"C\n" +
	"\x13FeedArticlesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"'\n" +
	"\x11GetArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x8b\x01\n" +
	"\x13ListArticlesRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1c\n" +
	"\tfavorited\x18\x03 \x01(\tR\tfavorited\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\"1\n" +
	"\x13UnfollowUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11FollowUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x93\x01\n" +
	"\x11UpdateUserRequest\x128\n" +
	"\x04user\x18\x01 \x01(\v2$.realworld.v1.UpdateUserRequest.UserR\x04user\x1aD\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\"\x17\n" +
	"\x15GetCurrentUserRequest\"}\n" +
	"\fLoginRequest\x123\n" +
	"\x04user\x18\x01 \x01(\v2\x1f.realworld.v1.LoginRequest.UserR\x04user\x1a8\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9f\x01\n" +
	"\x0fRegisterRequest\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".realworld.v1.RegisterRequest.UserR\x04user\x1aT\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xbb\x01\n" +
	"\fUserResponse\x123\n" +
	"\x04user\x18\x01 \x01(\v2\x1f.realworld.v1.UserResponse.UserR\x04user\x1av\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"\xbf\x01\n" +
	"\x0fProfileResponse\x12?\n" +
	"\aprofile\x18\x01 \x01(\v2%.realworld.v1.ProfileResponse.ProfileR\aprofile\x1ak\n" +
	"\aProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\"\xd2\x04\n" +
	"\x15SingleArticleResponse\x12E\n" +
	"\aarticle\x18\x01 \x01(\v2+.realworld.v1.SingleArticleResponse.ArticleR\aarticle\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\x1a\x85\x03\n" +
	"\aArticle\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x19\n" +
	"\btag_list\x18\x05 \x03(\tR\atagList\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tfavorited\x18\b \x01(\bR\tfavorited\x12'\n" +
	"\x0ffavorites_count\x18\t \x01(\rR\x0efavoritesCount\x12B\n" +
	"\x06author\x18\n" +
	" \x01(\v2*.realworld.v1.SingleArticleResponse.AuthorR\x06author\"\xef\x04\n" +
	"\x17MultipleArticleResponse\x12J\n" +
	"\barticles\x18\x01 \x03(\v2..realworld.v1.MultipleArticleResponse.ArticlesR\barticles\x12%\n" +
	"\x0earticles_count\x18\x02 \x01(\rR\rarticlesCount\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\x1a\xf4\x02\n" +
	"\bArticles\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\btag_list\x18\x04 \x03(\tR\atagList\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tfavorited\x18\a \x01(\bR\tfavorited\x12'\n" +
	"\x0ffavorites_count\x18\b \x01(\rR\x0efavoritesCount\x12D\n" +
	"\x06author\x18\t \x01(\v2,.realworld.v1.MultipleArticleResponse.AuthorR\x06author\"\xb4\x03\n" +
	"\x15SingleCommentResponse\x12E\n" +
	"\acomment\x18\x01 \x01(\v2+.realworld.v1.SingleCommentResponse.CommentR\acomment\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\x1a\xe7\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12B\n" +
	"\x06author\x18\x05 \x01(\v2*.realworld.v1.SingleCommentResponse.AuthorR\x06author\"\xbe\x03\n" +
	"\x17MultipleCommentResponse\x12J\n" +
	"\bcomments\x18\x01 \x03(\v2..realworld.v1.MultipleCommentResponse.CommentsR\bcomments\x1aj\n" +
	"\x06Author\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1c\n" +
	"\tfollowing\x18\x04 \x01(\bR\tfollowing\x1a\xea\x01\n" +
	"\bComments\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12D\n" +
	"\x06author\x18\x05 \x01(\v2,.realworld.v1.MultipleCommentResponse.AuthorR\x06author\"&\n" +
	"\x10TagsListResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2\xa6\x11\n" +
	"\tRealWorld\x12\\\n" +
	"\x05Login\x12\x1a.realworld.v1.LoginRequest\x1a\x1a.realworld.v1.UserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/users/login\x12\\\n" +
	"\bRegister\x12\x1d.realworld.v1.RegisterRequest\x1a\x1a.realworld.v1.UserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/users\x12d\n" +
	"\x0eGetCurrentUser\x12#.realworld.v1.GetCurrentUserRequest\x1a\x1a.realworld.v1.UserResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/user\x12_\n" +
	"\n" +
	"UpdateUser\x12\x1f.realworld.v1.UpdateUserRequest\x1a\x1a.realworld.v1.UserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/api/user\x12n\n" +
	"\n" +
	"GetProfile\x12\x1f.realworld.v1.GetProfileRequest\x1a\x1d.realworld.v1.ProfileResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/profiles/{username}\x12x\n" +
	"\n" +
	"FollowUser\x12\x1f.realworld.v1.FollowUserRequest\x1a\x1d.realworld.v1.ProfileResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/profiles/{username}/follow\x12y\n" +
	"\fUnfollowUser\x12!.realworld.v1.UnfollowUserRequest\x1a\x1d.realworld.v1.ProfileResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/api/profiles/{username}/follow\x12o\n" +
	"\fListArticles\x12!.realworld.v1.ListArticlesRequest\x1a%.realworld.v1.MultipleArticleResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/articles\x12t\n" +
	"\fFeedArticles\x12!.realworld.v1.FeedArticlesRequest\x1a%.realworld.v1.MultipleArticleResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/articles/feed\x12p\n" +
	"\n" +
	"GetArticle\x12\x1f.realworld.v1.GetArticleRequest\x1a#.realworld.v1.SingleArticleResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/articles/{slug}\x12r\n" +
	"\rCreateArticle\x12\".realworld.v1.CreateArticleRequest\x1a#.realworld.v1.SingleArticleResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/articles\x12y\n" +
	"\rUpdateArticle\x12\".realworld.v1.UpdateArticleRequest\x1a#.realworld.v1.SingleArticleResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/articles/{slug}\x12v\n" +
	"\rDeleteArticle\x12\".realworld.v1.DeleteArticleRequest\x1a#.realworld.v1.DeleteArticleResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/articles/{slug}\x12|\n" +
	"\n" +
	"AddComment\x12\x1f.realworld.v1.AddCommentRequest\x1a#.realworld.v1.SingleCommentResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/articles/{slug}/comments\x12}\n" +
	"\vGetComments\x12 .realworld.v1.GetCommentsRequest\x1a%.realworld.v1.MultipleCommentResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/articles/{slug}/comments\x12\x84\x01\n" +
	"\rDeleteComment\x12\".realworld.v1.DeleteCommentRequest\x1a#.realworld.v1.DeleteCommentResponse\"*\x82\xd3\xe4\x93\x02$*\"/api/articles/{slug}/comments/{id}\x12\x86\x01\n" +
	"\x0fFavoriteArticle\x12$.realworld.v1.FavoriteArticleRequest\x1a#.realworld.v1.SingleArticleResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/articles/{slug}/favorite\x12\x87\x01\n" +
	"\x11UnfavoriteArticle\x12&.realworld.v1.UnfavoriteArticleRequest\x1a#.realworld.v1.SingleArticleResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/articles/{slug}/favorite\x12Z\n" +
	"\aGetTags\x12\x1c.realworld.v1.GetTagsRequest\x1a\x1e.realworld.v1.TagsListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/tagsB&Z$kratos-realworld/api/realworld/v1;v1b\x06proto3"

var (
	file_realworld_v1_realworld_proto_rawDescOnce sync.Once
	file_realworld_v1_realworld_proto_rawDescData []byte
)

func file_realworld_v1_realworld_proto_rawDescGZIP() []byte {
	file_realworld_v1_realworld_proto_rawDescOnce.Do(func() {
		file_realworld_v1_realworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realworld_v1_realworld_proto_rawDesc), len(file_realworld_v1_realworld_proto_rawDesc)))
	})
	return file_realworld_v1_realworld_proto_rawDescData
}

var file_realworld_v1_realworld_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_realworld_v1_realworld_proto_goTypes = []any{
	(*GetTagsRequest)(nil),                   // 0: realworld.v1.GetTagsRequest
	(*FavoriteArticleRequest)(nil),           // 1: realworld.v1.FavoriteArticleRequest
	(*UnfavoriteArticleRequest)(nil),         // 2: realworld.v1.UnfavoriteArticleRequest
	(*DeleteCommentRequest)(nil),             // 3: realworld.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),            // 4: realworld.v1.DeleteCommentResponse
	(*GetCommentsRequest)(nil),               // 5: realworld.v1.GetCommentsRequest
	(*AddCommentRequest)(nil),                // 6: realworld.v1.AddCommentRequest
	(*DeleteArticleRequest)(nil),             // 7: realworld.v1.DeleteArticleRequest
	(*DeleteArticleResponse)(nil),            // 8: realworld.v1.DeleteArticleResponse
	(*UpdateArticleRequest)(nil),             // 9: realworld.v1.UpdateArticleRequest
	(*CreateArticleRequest)(nil),             // 10: realworld.v1.CreateArticleRequest
	(*FeedArticlesRequest)(nil),              // 11: realworld.v1.FeedArticlesRequest
	(*GetArticleRequest)(nil),                // 12: realworld.v1.GetArticleRequest
	(*ListArticlesRequest)(nil),              // 13: realworld.v1.ListArticlesRequest
	(*UnfollowUserRequest)(nil),              // 14: realworld.v1.UnfollowUserRequest
	(*FollowUserRequest)(nil),                // 15: realworld.v1.FollowUserRequest
	(*GetProfileRequest)(nil),                // 16: realworld.v1.GetProfileRequest
	(*UpdateUserRequest)(nil),                // 17: realworld.v1.UpdateUserRequest
	(*GetCurrentUserRequest)(nil),            // 18: realworld.v1.GetCurrentUserRequest
	(*LoginRequest)(nil),                     // 19: realworld.v1.LoginRequest
	(*RegisterRequest)(nil),                  // 20: realworld.v1.RegisterRequest
	(*UserResponse)(nil),                     // 21: realworld.v1.UserResponse
	(*ProfileResponse)(nil),                  // 22: realworld.v1.ProfileResponse
	(*SingleArticleResponse)(nil),            // 23: realworld.v1.SingleArticleResponse
	(*MultipleArticleResponse)(nil),          // 24: realworld.v1.MultipleArticleResponse
	(*SingleCommentResponse)(nil),            // 25: realworld.v1.SingleCommentResponse
	(*MultipleCommentResponse)(nil),          // 26: realworld.v1.MultipleCommentResponse
	(*TagsListResponse)(nil),                 // 27: realworld.v1.TagsListResponse
	(*AddCommentRequest_Comment)(nil),        // 28: realworld.v1.AddCommentRequest.Comment
	(*UpdateArticleRequest_Article)(nil),     // 29: realworld.v1.UpdateArticleRequest.Article
	(*CreateArticleRequest_Article)(nil),     // 30: realworld.v1.CreateArticleRequest.Article
	(*UpdateUserRequest_User)(nil),           // 31: realworld.v1.UpdateUserRequest.User
	(*LoginRequest_User)(nil),                // 32: realworld.v1.LoginRequest.User
	(*RegisterRequest_User)(nil),             // 33: realworld.v1.RegisterRequest.User
	(*UserResponse_User)(nil),                // 34: realworld.v1.UserResponse.User
	(*ProfileResponse_Profile)(nil),          // 35: realworld.v1.ProfileResponse.Profile
	(*SingleArticleResponse_Author)(nil),     // 36: realworld.v1.SingleArticleResponse.Author
	(*SingleArticleResponse_Article)(nil),    // 37: realworld.v1.SingleArticleResponse.Article
	(*MultipleArticleResponse_Author)(nil),   // 38: realworld.v1.MultipleArticleResponse.Author
	(*MultipleArticleResponse_Articles)(nil), // 39: realworld.v1.MultipleArticleResponse.Articles
	(*SingleCommentResponse_Author)(nil),     // 40: realworld.v1.SingleCommentResponse.Author
	(*SingleCommentResponse_Comment)(nil),    // 41: realworld.v1.SingleCommentResponse.Comment
	(*MultipleCommentResponse_Author)(nil),   // 42: realworld.v1.MultipleCommentResponse.Author
	(*MultipleCommentResponse_Comments)(nil), // 43: realworld.v1.MultipleCommentResponse.Comments
	(*timestamppb.Timestamp)(nil),            // 44: google.protobuf.Timestamp
}
var file_realworld_v1_realworld_proto_depIdxs = []int32{
	28, // 0: realworld.v1.AddCommentRequest.comment:type_name -> realworld.v1.AddCommentRequest.Comment
	29, // 1: realworld.v1.UpdateArticleRequest.article:type_name -> realworld.v1.UpdateArticleRequest.Article
	30, // 2: realworld.v1.CreateArticleRequest.article:type_name -> realworld.v1.CreateArticleRequest.Article
	31, // 3: realworld.v1.UpdateUserRequest.user:type_name -> realworld.v1.UpdateUserRequest.User
	32, // 4: realworld.v1.LoginRequest.user:type_name -> realworld.v1.LoginRequest.User
	33, // 5: realworld.v1.RegisterRequest.user:type_name -> realworld.v1.RegisterRequest.User
	34, // 6: realworld.v1.UserResponse.user:type_name -> realworld.v1.UserResponse.User
	35, // 7: realworld.v1.ProfileResponse.profile:type_name -> realworld.v1.ProfileResponse.Profile
	37, // 8: realworld.v1.SingleArticleResponse.article:type_name -> realworld.v1.SingleArticleResponse.Article
	39, // 9: realworld.v1.MultipleArticleResponse.articles:type_name -> realworld.v1.MultipleArticleResponse.Articles
	41, // 10: realworld.v1.SingleCommentResponse.comment:type_name -> realworld.v1.SingleCommentResponse.Comment
	43, // 11: realworld.v1.MultipleCommentResponse.comments:type_name -> realworld.v1.MultipleCommentResponse.Comments
	44, // 12: realworld.v1.SingleArticleResponse.Article.created_at:type_name -> google.protobuf.Timestamp
	44, // 13: realworld.v1.SingleArticleResponse.Article.updated_at:type_name -> google.protobuf.Timestamp
	36, // 14: realworld.v1.SingleArticleResponse.Article.author:type_name -> realworld.v1.SingleArticleResponse.Author
	44, // 15: realworld.v1.MultipleArticleResponse.Articles.created_at:type_name -> google.protobuf.Timestamp
	44, // 16: realworld.v1.MultipleArticleResponse.Articles.updated_at:type_name -> google.protobuf.Timestamp
	38, // 17: realworld.v1.MultipleArticleResponse.Articles.author:type_name -> realworld.v1.MultipleArticleResponse.Author
	44, // 18: realworld.v1.SingleCommentResponse.Comment.created_at:type_name -> google.protobuf.Timestamp
	44, // 19: realworld.v1.SingleCommentResponse.Comment.updated_at:type_name -> google.protobuf.Timestamp
	40, // 20: realworld.v1.SingleCommentResponse.Comment.author:type_name -> realworld.v1.SingleCommentResponse.Author
	44, // 21: realworld.v1.MultipleCommentResponse.Comments.created_at:type_name -> google.protobuf.Timestamp
	44, // 22: realworld.v1.MultipleCommentResponse.Comments.updated_at:type_name -> google.protobuf.Timestamp
	42, // 23: realworld.v1.MultipleCommentResponse.Comments.author:type_name -> realworld.v1.MultipleCommentResponse.Author
	19, // 24: realworld.v1.RealWorld.Login:input_type -> realworld.v1.LoginRequest
	20, // 25: realworld.v1.RealWorld.Register:input_type -> realworld.v1.RegisterRequest
	18, // 26: realworld.v1.RealWorld.GetCurrentUser:input_type -> realworld.v1.GetCurrentUserRequest
	17, // 27: realworld.v1.RealWorld.UpdateUser:input_type -> realworld.v1.UpdateUserRequest
	16, // 28: realworld.v1.RealWorld.GetProfile:input_type -> realworld.v1.GetProfileRequest
	15, // 29: realworld.v1.RealWorld.FollowUser:input_type -> realworld.v1.FollowUserRequest
	14, // 30: realworld.v1.RealWorld.UnfollowUser:input_type -> realworld.v1.UnfollowUserRequest
	13, // 31: realworld.v1.RealWorld.ListArticles:input_type -> realworld.v1.ListArticlesRequest
	11, // 32: realworld.v1.RealWorld.FeedArticles:input_type -> realworld.v1.FeedArticlesRequest
	12, // 33: realworld.v1.RealWorld.GetArticle:input_type -> realworld.v1.GetArticleRequest
	10, // 34: realworld.v1.RealWorld.CreateArticle:input_type -> realworld.v1.CreateArticleRequest
	9,  // 35: realworld.v1.RealWorld.UpdateArticle:input_type -> realworld.v1.UpdateArticleRequest
	7,  // 36: realworld.v1.RealWorld.DeleteArticle:input_type -> realworld.v1.DeleteArticleRequest
	6,  // 37: realworld.v1.RealWorld.AddComment:input_type -> realworld.v1.AddCommentRequest
	5,  // 38: realworld.v1.RealWorld.GetComments:input_type -> realworld.v1.GetCommentsRequest
	3,  // 39: realworld.v1.RealWorld.DeleteComment:input_type -> realworld.v1.DeleteCommentRequest
	1,  // 40: realworld.v1.RealWorld.FavoriteArticle:input_type -> realworld.v1.FavoriteArticleRequest
	2,  // 41: realworld.v1.RealWorld.UnfavoriteArticle:input_type -> realworld.v1.UnfavoriteArticleRequest
	0,  // 42: realworld.v1.RealWorld.GetTags:input_type -> realworld.v1.GetTagsRequest
	21, // 43: realworld.v1.RealWorld.Login:output_type -> realworld.v1.UserResponse
	21, // 44: realworld.v1.RealWorld.Register:output_type -> realworld.v1.UserResponse
	21, // 45: realworld.v1.RealWorld.GetCurrentUser:output_type -> realworld.v1.UserResponse
	21, // 46: realworld.v1.RealWorld.UpdateUser:output_type -> realworld.v1.UserResponse
	22, // 47: realworld.v1.RealWorld.GetProfile:output_type -> realworld.v1.ProfileResponse
	22, // 48: realworld.v1.RealWorld.FollowUser:output_type -> realworld.v1.ProfileResponse
	22, // 49: realworld.v1.RealWorld.UnfollowUser:output_type -> realworld.v1.ProfileResponse
	24, // 50: realworld.v1.RealWorld.ListArticles:output_type -> realworld.v1.MultipleArticleResponse
	24, // 51: realworld.v1.RealWorld.FeedArticles:output_type -> realworld.v1.MultipleArticleResponse
	23, // 52: realworld.v1.RealWorld.GetArticle:output_type -> realworld.v1.SingleArticleResponse
	23, // 53: realworld.v1.RealWorld.CreateArticle:output_type -> realworld.v1.SingleArticleResponse
	23, // 54: realworld.v1.RealWorld.UpdateArticle:output_type -> realworld.v1.SingleArticleResponse
	8,  // 55: realworld.v1.RealWorld.DeleteArticle:output_type -> realworld.v1.DeleteArticleResponse
	25, // 56: realworld.v1.RealWorld.AddComment:output_type -> realworld.v1.SingleCommentResponse
	26, // 57: realworld.v1.RealWorld.GetComments:output_type -> realworld.v1.MultipleCommentResponse
	4,  // 58: realworld.v1.RealWorld.DeleteComment:output_type -> realworld.v1.DeleteCommentResponse
	23, // 59: realworld.v1.RealWorld.FavoriteArticle:output_type -> realworld.v1.SingleArticleResponse
	23, // 60: realworld.v1.RealWorld.UnfavoriteArticle:output_type -> realworld.v1.SingleArticleResponse
	27, // 61: realworld.v1.RealWorld.GetTags:output_type -> realworld.v1.TagsListResponse
	43, // [43:62] is the sub-list for method output_type
	24, // [24:43] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_realworld_v1_realworld_proto_init() }
func file_realworld_v1_realworld_proto_init() {
	if File_realworld_v1_realworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realworld_v1_realworld_proto_rawDesc), len(file_realworld_v1_realworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realworld_v1_realworld_proto_goTypes,
		DependencyIndexes: file_realworld_v1_realworld_proto_depIdxs,
		MessageInfos:      file_realworld_v1_realworld_proto_msgTypes,
	}.Build()
	File_realworld_v1_realworld_proto = out.File
	file_realworld_v1_realworld_proto_goTypes = nil
	file_realworld_v1_realworld_proto_depIdxs = nil
}
